export enum IconType {
  Archive = 'archive',
  BarChart = 'barChart',
  Bookmark = 'bookmark',
  BookOpen = 'bookOpen',
  Cart = 'cart',
  Diagram = 'diagram',
  Dollar = 'dollar',
  DollarOutline = 'dollarOutline',
  Envelope = 'envelope',
  Image = 'image',
  Search = 'search',
  Settings = 'settings',
  Shop = 'shop',
}
